### ISSUE TITLE
fix: probabilistic test failures

### ISSUE THREAD

**Issue by laysakura** [SpringQL/SpringQL#71]
use single thread for tests asserting some values?

**Comment by laysakura** [comment]
## Latest 10 test failures and possible causes


- https://github.com/SpringQL/SpringQL/runs/5825844630?check_suite_focus=true

    ```
    test test_feat_left_outer_join ... FAILED
        Diff < left / right > :
        <2
        >3
    

        ': springql-core/tests/feat_join.rs:152
           0: log_panics::init::{{closure}}
    ```

- https://github.com/SpringQL/SpringQL/runs/5825844880?check_suite_focus=true

    ```
    [2022-04-05T00:13:11Z ERROR panic] thread 'GenericWorker' panicked at 'task id Pump { id: "pu_join", input_type: Window } does not have upstream source_city_temperature': springql-core/src/stream_engine/autonomous_executor/task_graph.rs:111

    ...

    [2022-04-05T00:13:12Z ERROR panic] thread 'test_feat_left_outer_join' panicked at 'failed to wait for worker thread to finish its job: SendError { .. }': springql-core/src/stream_engine/autonomous_executor/worker/worker_handle.rs:42
    ```

**Comment by laysakura** [comment]
does not reproduce with:

```rust
    config.worker.n_generic_worker_threads = 1;
    config.worker.n_source_worker_threads = 1;
```

**Comment by laysakura** [comment]
hypothesis:

Every source worker and generic worker may hold different Pipeline (it's updated via event sourcing).
A generic worker may discard rows if it does not recognize downstream queues.

**Comment by laysakura** [comment]
## Remaining issues

The above cause cannot explain the following issue:

- https://github.com/SpringQL/SpringQL/runs/5825844880?check_suite_focus=true

    ```
    [2022-04-05T00:13:11Z ERROR panic] thread 'GenericWorker' panicked at 'task id Pump { id: "pu_join", input_type: Window } does not have upstream source_city_temperature': springql-core/src/stream_engine/autonomous_executor/task_graph.rs:111

    ...

    [2022-04-05T00:13:12Z ERROR panic] thread 'test_feat_left_outer_join' panicked at 'failed to wait for worker thread to finish its job: SendError { .. }': springql-core/src/stream_engine/autonomous_executor/worker/worker_handle.rs:42
    ```

Created: ...

**Comment by laysakura** [comment]
## Solution

- Make `n_*_threads = 1` as default to keep **in-order** processing.
- Documents `n_*_threads > 1` can lead to **out-of-order** processing.
