### ISSUE TITLE
bug: task id Pump { id: "pu_join", input_type: Window } does not have upstream source_city_temperature

### ISSUE THREAD

**Issue by laysakura** [SpringQL/SpringQL#80]
refs: https://github.com/SpringQL/SpringQL/issues/71#issuecomment-1089939069

- https://github.com/SpringQL/SpringQL/runs/5825844880?check_suite_focus=true `test_feat_left_outer_join`

    ```
    [2022-04-05T00:13:11Z ERROR panic] thread 'GenericWorker' panicked at 'task id Pump { id: "pu_join", input_type: Window } does not have upstream source_city_temperature': springql-core/src/stream_engine/autonomous_executor/task_graph.rs:111

    ...

    [2022-04-05T00:13:12Z ERROR panic] thread 'test_feat_left_outer_join' panicked at 'failed to wait for worker thread to finish its job: SendError { .. }': springql-core/src/stream_engine/autonomous_executor/worker/worker_handle.rs:42
    ```

**Comment by laysakura** [comment]
reproduced: https://github.com/SpringQL/SpringQL/runs/5849495920?check_suite_focus=true
